### ISSUE TITLE
Support for UTF-8 charset

### ISSUE THREAD

**Issue by houhr** [dlmanning/gulp-sass#10]
It seems that the current edition of gulp-sass cannot handle Chinese comments correctly, but the original `sass` command line tool can do it correctly with a line of `@charset "UTF-8";` at the output css file's beginning. Hope this bug can be fixed in the near future. Thanks.

**Comment by Snugug** [comment]
This has been [resolved in 2.x](https://github.com/dlmanning/gulp-sass/blob/2.x). Please try it and report back. If we don't hear back, we'll assume it's been resolved and close this issue.

```
npm install dlmanning/gulp-sass#2.x
```

**Comment by Snugug** [comment]
As it's been a month, I'm closing this.

**Comment by yohikofox** [comment]
Hi, i am using "gulp-sass": "^2.3.2", and i still have the issue.

"\f26e" text is still badly transpiled :(
