### ISSUE TITLE
Failed at the node-sass@4.7.2 postinstall script.

### ISSUE THREAD

**Issue by nikbelikov** [dlmanning/gulp-sass#652]
```
➜  20th-century git:(master) ✗ node -v && npm -v
v8.9.4
5.6.0
➜  20th-century git:(master) ✗ sudo npm i gulp-sass -ES

> node-sass@4.7.2 install /Users/nikbelikov/Documents/20th-century/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/nikbelikov/Documents/20th-century/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/nikbelikov/Documents/20th-century/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/nikbelikov/Documents/20th-century/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /Users/nikbelikov/Documents/20th-century/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/nikbelikov/Documents/20th-century/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/nikbelikov/Documents/20th-century/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:13:12)\n    at F (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:68:19)\n    at E (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:80:29)\n    at /Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:89:16\n    at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/index.js:42:5\n    at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.4
gyp verb build dir attempting to create "build" dir: /Users/nikbelikov/Documents/20th-century/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/build'
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/nikbelikov/Documents/20th-century/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/nikbelikov/Documents/20th-century/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN 20th-century@ No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nikbelikov/.npm/_logs/2018-01-25T13_04_57_833Z-debug.log
➜  20th-century git:(master) ✗ sudo npm r gulp-sass -ES
npm WARN 20th-century@ No repository field.

removed 2 packages in 7.124s
➜  20th-century git:(master) ✗ sudo npm i gulp-sass -ES

> node-sass@4.7.2 install /Users/nikbelikov/Documents/20th-century/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/nikbelikov/Documents/20th-century/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/nikbelikov/Documents/20th-century/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/nikbelikov/Documents/20th-century/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/scripts/install.js:111:11)
    at Object.<anonymous> (/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/scripts/install.js:154:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/vendor' }

> node-sass@4.7.2 postinstall /Users/nikbelikov/Documents/20th-century/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/nikbelikov/Documents/20th-century/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/nikbelikov/Documents/20th-century/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:13:12)\n    at F (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:68:19)\n    at E (/Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:80:29)\n    at /Users/nikbelikov/Documents/20th-century/node_modules/which/which.js:89:16\n    at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/index.js:42:5\n    at /Users/nikbelikov/Documents/20th-century/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.4
gyp verb build dir attempting to create "build" dir: /Users/nikbelikov/Documents/20th-century/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/build'
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/Users/nikbelikov/Documents/20th-century/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/nikbelikov/Documents/20th-century/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN 20th-century@ No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nikbelikov/.npm/_logs/2018-01-25T13_07_31_815Z-debug.log
➜  20th-century git:(master) ✗ 

```

**Comment by roymj88** [comment]
Any update on this? Did you get it resolved?

**Comment by nikbelikov** [comment]
Nope :|

**Comment by xzyfer** [comment]
The error message states this is a permission issue. There's nothing to be
done in gulp-sass.

Unable to save binary
/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/vendor/darwin-x64-57
: { Error: EACCES: permission denied, mkdir
'/Users/nikbelikov/Documents/20th-century/node_modules/node-sass/vendor'

**Comment by krayushfk** [comment]
Same issue has been faced by a lot of people
and the worst part is: none of the developers are trying to fix this.
I can paste 15-20 links pointing to this repository and still this issue persists!

**Comment by nikbelikov** [comment]
@krayushfk I use that flag `--unsafe-perm=true` Hope that it will help you too.
```
sudo npm i gulp-sass -ES --unsafe-perm=true
```

**Comment by krayushfk** [comment]
@xzyfer: Little help needed here man!
A lot of devs are facing this issue.
Can you please help!

**Comment by krayushfk** [comment]
@nikbelikov: Thanks for the reply but that didn't work as well

```
Binary found at /var/lib/jenkins/jobs/capacity-planner-ui/workspace/tmp/src/github.com/Flipkart/capacity-planner-ui/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Segmentation fault
npm ERR! code ELIFECYCLE
npm ERR! errno 139
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 139
```

**Comment by nikbelikov** [comment]
Don't understand what's going on. The other packages installs with no problems.

**Comment by kodemasta** [comment]
getting this:

Binary has a problem: [Error: .../node_modules/node-sass/vendor/linux-x64-46/binding.node: ELF file OS ABI invalid]

2018-02-06 17:22:55 gobuilds.Compile : npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
2018-02-06 17:22:55 gobuilds.Compile : npm ERR! Exit status 1

**Comment by xzyfer** [comment]
@kodemasta see https://github.com/sass/node-sass/issues/2159 for discussion on this issue

**Comment by ArnoldLC** [comment]
@nikbelikov In my case, also I had to delete the **package-lock.json** and work normally.

**Comment by xzyfer** [comment]
npm update node-sass@late will do everything you need.

**Comment by adamklepacz** [comment]
Had the same issue a few seconds ago. Deleting package-lock.json helped me! Thanks a lot, people!

**Comment by akshayseth** [comment]
@kwoncheol You my man.It works with the following command guys.
sudo rm -rf node_modules && npm rebuild node-sass && npm i
Thanks a lot @kwoncheol

**Comment by kennyalmendral** [comment]
Thanks guys and @akshayseth, `npm rebuild node-sass && npm i` worked for me...

**Comment by berry807** [comment]
And incase for someone who uses yarn you have to remove `yarn.lock`

**Comment by 2478535322** [comment]
Reason: the node-sass folder you downloaded when npm install is empty
- In 'C:\Users\Administrator\AppData\Roaming\npm-cache\node-sass\4.7.2\

Solution: download it by yourself with npm I node-sass
- In "C:\Users\Administrator\AppData\Roaming\npm-cache\node-sass\4.7.2\ '", there will be a file win32-x64-57_binding , Copy this file under 3.13.1 and then re-install npm install

**Comment by 2478535322** [comment]
Reason: the node-sass folder you downloaded when npm install is empty

In 'C:\Users\Administrator\AppData\Roaming\npm-cache\node-sass\4.7.2\
Solution: download it by yourself with npm I node-sass

In "C:\Users\Administrator\AppData\Roaming\npm-cache\node-sass\4.7.2\ '", there will be a file win32-x64-57_binding , Copy this file under 4.7.2 and then re-install npm install

**Comment by zinmyoswe** [comment]
Deleting package.json and run again `npm install` solve my issue. Thank SarahPhuong

**Comment by nvrr** [comment]
ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NVRR\AppData\Roaming\npm-cache\_logs\2019-12-14T11_25_09_705Z-debug.log
PS C:\Users\NVRR\documents\cera\Bootstrap4\conFusion> npm install --save-dev node-sass@4.7.2
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).




how to fix this

and also showsnpm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

 when try to do    npm install --save-dev node-sass@4.7.2

i try above mention commands in comments too

**Comment by nvrr** [comment]
> @nikbelikov Thanks. It works for me!
> 
> **$ sudo npm install node-sass --save-dev --unsafe-perm=true**

this works for me  but how to change version 4.13.0 to 4.7.2 (i follow the course in cousera  they shows this version so it may help in further for course

**Comment by josealarconchacon** [comment]
@nikbelikov Thank you.

**Comment by ranjan900795** [comment]
never run npm command with sudo
change the ownership of your folder using sudo chown -R /Users/nikbelikov/Documents/20th-century/
then do npm install whatever you want to

**Comment by vartikaNits** [comment]
> @nikbelikov Thanks. It works for me!
> 
> **$ sudo npm install node-sass --save-dev --unsafe-perm=true**

Thank-you so much! It solved my problem.
